=== bgidley/zebra/import/java/antelope/src/webapp/WEB-INF/conf/Validation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT args (argument*)>

<!ELEMENT argument EMPTY>
<!ATTLIST argument
	name NMTOKEN #REQUIRED
	type (string | int ) "string"
	value CDATA #REQUIRED
>

<!ELEMENT named-validator EMPTY>
<!ATTLIST named-validator name NMTOKEN #REQUIRED>

<!ELEMENT parameter-validator (args,validators)>
<!ATTLIST parameter-validator name CDATA #REQUIRED>

<!ELEMENT parametervalidators (parameter-validator*)>

<!ELEMENT request-validator (args?,validators?)>


<!ELEMENT validation (parametervalidators,request-validator)>
<!ATTLIST validation requestLookupKey CDATA #REQUIRED>

<!ELEMENT validator (args)>
<!ATTLIST validator class NMTOKEN #REQUIRED>


<!ELEMENT validators (validator*,named-validator*)>

=== bgidley/zebra/import/java/antelope/src/webapp/WEB-INF/review/rules/action.StartProcess.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.StartProcess">
  <!--Validation Specification : action.StartProcess-->
  <parametervalidators>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="template">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="processname">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="nocacheid">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator />
</validation>

=== bgidley/zebra/import/java/antelope/src/webapp/WEB-INF/review/rules/customised/action-user.DeleteUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.user.DeleteUser">
  <!--Validation Specification : action.user_DeleteUser-->
  <parametervalidators>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="template">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="username">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator>
    <args />
    <validators>
      <validator class="com.anite.antelope.validation.NotNullValidator">
        <args>
          <!-- Arguments for NotNullValidator -->
          <argument name="isNullMessage" type="string" value="You must select a user." />
          <argument name="keys" type="string" value="username" />
        </args>
      </validator>
    </validators>
  </request-validator>
</validation>

=== bgidley/zebra/import/java/antelope/src/webapp/WEB-INF/review/rules/customised/action-formSample.SimpleFormSubmit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.formSample.SimpleFormSubmit">
  <!--Validation Specification : action.formSample_SimpleFormSubmit-->
  <parametervalidators>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="passwordfield">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="textfield">
      <args />
      <validators>
        <validator class="com.anite.antelope.validation.FormMaxLengthValidator">
          <args>
            <argument name="maxlength" type="int" value="30" />
            <argument name="inputTooLongMessage" type="string" value="This item must be less than 30 characters in length. Please re-enter." />
          </args>
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="checkfield">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator>
    <args />
    <validators>
      <validator class="com.anite.antelope.validation.NotNullValidator">
        <args>
          <!-- Arguments for NotNullValidator -->
          <argument name="isNullMessage" type="string" value="Please enter a text value." />
          <argument name="keys" type="string" value="textfield" />
        </args>
      </validator>
      <validator class="com.anite.antelope.validation.NotNullValidator">
        <args>
          <!-- Arguments for NotNullValidator -->
          <argument name="isNullMessage" type="string" value="Please select a animal." />
          <argument name="keys" type="string" value="checkfield" />
        </args>
      </validator>
    </validators>
  </request-validator>
</validation>

=== bgidley/zebra/src/java/antelope/src/webapp/WEB-INF/review/rules/customised/action-user.AddUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.user.AddUser">
  <!--Validation Specification : action.user_AddUser-->
  <parametervalidators>
    <parameter-validator name="confpassword">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="password">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>    
    <parameter-validator name="username">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator>
    <args />
    <validators>
      <validator class="com.anite.antelope.validation.NotNullValidator">
        <args>
          <!-- Arguments for NotNullValidator -->
          <argument name="isNullMessage" type="string" value="Please enter a user name." />
          <argument name="keys" type="string" value="username" />
        </args>
      </validator>
      <validator class="com.anite.antelope.validation.NotNullValidator">
        <args>
          <!-- Arguments for NotNullValidator -->
          <argument name="isNullMessage" type="string" value="Please enter a password." />
          <argument name="keys" type="string" value="password" />
        </args>
      </validator>
      <validator class="com.anite.antelope.validation.NotNullValidator">
        <args>
          <!-- Arguments for NotNullValidator -->
          <argument name="isNullMessage" type="string" value="Please confirm your password." />
          <argument name="keys" type="string" value="confpassword" />
        </args>
      </validator>
    </validators>
  </request-validator>
</validation>

=== bgidley/zebra/src/java/antelope/src/webapp/WEB-INF/review/rules/action.myFirstWorkflow.HowOldAreYouAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.myFirstWorkflow.HowOldAreYouAction">
  <!--Validation Specification : action.myFirstWorkflow.HowOldAreYouAction-->
  <parametervalidators>
    <parameter-validator name="template">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="nocacheid">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator />
</validation>

=== bgidley/zebra/import/java/antelope/src/webapp/WEB-INF/review/rules/customised/action.myFirstWorkflow.HelloAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.myFirstWorkflow.HelloAction">
  <!--Validation Specification : action.myFirstWorkflow.HelloAction-->
  <parametervalidators>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="pause">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="name">
      <args />
      <validators>
        <validator class="com.anite.antelope.validation.NotNullValidator">
          <args>
            <!-- Arguments for NotNullValidator -->
            <argument name="isNullMessage" type="string" value="Please enter a name." />
            <argument name="keys" type="string" value="name" />
          </args>
        </validator>
        <validator class="com.anite.antelope.validation.FormMaxLengthValidator">
          <args>
            <argument name="maxlength" type="int" value="60" />
            <argument name="inputTooLongMessage" type="string" value="This item must be less than 60 characters in length. Please re-enter." />
          </args>
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="done">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator />
</validation>

=== bgidley/zebra/import/java/antelope/src/webapp/WEB-INF/review/rules/action.LoginUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.LoginUser">
  <!--Validation Specification : action.LoginUser-->
  <parametervalidators>
    <parameter-validator name="password">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="template">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="username">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="nocacheid">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator />
</validation>

=== bgidley/zebra/src/java/antelope/src/webapp/WEB-INF/review/rules/customised/action-user.ChangePermission.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.user.ChangePermission">
  <!--Validation Specification : action.user_ChangePermission-->
  <parametervalidators>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="template">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="doaddgroup">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="doremovegroup">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="adduser">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="deleteuser">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="username">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="availablegroups">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="allocatedgroups">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator>
    <args />
    <validators>
      <validator class="com.anite.antelope.validation.NotNullValidator">
        <args>
          <!-- Arguments for NotNullValidator -->
          <argument name="isNullMessage" type="string" value="Please select a user." />
          <argument name="keys" type="string" value="username" />
        </args>
      </validator>
    </validators>
  </request-validator>
</validation>
