=== bgidley/zebra/import/java/antelope/src/webapp/WEB-INF/conf/Validation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT args (argument*)>

<!ELEMENT argument EMPTY>
<!ATTLIST argument
	name NMTOKEN #REQUIRED
	type (string | int ) "string"
	value CDATA #REQUIRED
>

<!ELEMENT named-validator EMPTY>
<!ATTLIST named-validator name NMTOKEN #REQUIRED>

<!ELEMENT parameter-validator (args,validators)>
<!ATTLIST parameter-validator name CDATA #REQUIRED>

<!ELEMENT parametervalidators (parameter-validator*)>

<!ELEMENT request-validator (args?,validators?)>


<!ELEMENT validation (parametervalidators,request-validator)>
<!ATTLIST validation requestLookupKey CDATA #REQUIRED>

<!ELEMENT validator (args)>
<!ATTLIST validator class NMTOKEN #REQUIRED>


<!ELEMENT validators (validator*,named-validator*)>

=== bgidley/zebra/src/java/antelope/src/webapp/WEB-INF/review/rules/customised/action.myFirstWorkflow.HowOldAreYouAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.myFirstWorkflow.HowOldAreYouAction">
  <!--Validation Specification : action.myFirstWorkflow.HowOldAreYouAction-->
  <parametervalidators>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="age">
      <args />
      <validators>
        <validator class="com.anite.antelope.validation.IntegerValidator">
          <args>
            <argument name="failedMessage" type="string" value="Invalid Integer, please re-enter" />
          </args>
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="done">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator />
</validation>

=== bgidley/zebra/import/java/antelope/src/webapp/WEB-INF/review/rules/customised/action.myFirstWorkflow.EnterExpiryDateAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validation PUBLIC "-//Apache//TEXT Validation//EN" "http://purl.oclc.org/NET/turbine-review/Validation.dtd">

<validation requestLookupKey="action.myFirstWorkflow.EnterExpiryDateAction">
  <!--Validation Specification : action.myFirstWorkflow.EnterExpiryDateAction-->
  <parametervalidators>
    <parameter-validator name="action">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="expiry">
      <args />
      <validators>
        <validator class="com.anite.antelope.validation.FormattedDateValidator">
          <args>
            <argument name="failedMessage" type="string" value="Invalid Date, please re-enter" />
          </args>
        </validator>
      </validators>
    </parameter-validator>
    <parameter-validator name="done">
      <args />
      <validators>
        <validator class="org.apache.turbine.component.review.validators.AlwaysTrueValidator">
          <args />
        </validator>
      </validators>
    </parameter-validator>
  </parametervalidators>
  <request-validator />
</validation>
